AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - ./*.gemspec

Metrics/PerceivedComplexity:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: false
  
Metrics/CyclomaticComplexity:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatString:
  Enabled: false
  
Style/PerlBackrefs:
  Enabled: false
  
Style/GlobalVars:
  Enabled: false
  
Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
  
Lint/MissingCopEnableDirective:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/ClassVars:
  Enabled: false
