AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - ./*.gemspec
  NewCops: enable

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/StderrPuts:
  Enabled: false
